ALTER TABLE intents
  DROP CONSTRAINT IF EXISTS intents_rail_check,
  ADD CONSTRAINT intents_rail_check
  CHECK (rail IN ('CCTP','AXELAR','LAYERZERO','VIA_LABS','WORMHOLE','THORCHAIN','GASZIP','HYPERLANE_NEXUS','OPTIMISM_NATIVE_BRIDGE','CHAINFLIP','MAYA','TELESWAP'));

ALTER TABLE intents
  DROP CONSTRAINT IF EXISTS intents_fallback_rail_check,
  ADD CONSTRAINT intents_fallback_rail_check
  CHECK (fallback_rail IS NULL OR fallback_rail IN ('CCTP','AXELAR','LAYERZERO','VIA_LABS','WORMHOLE','THORCHAIN','GASZIP','HYPERLANE_NEXUS','OPTIMISM_NATIVE_BRIDGE','CHAINFLIP','MAYA','TELESWAP'));

ALTER TABLE intent_rail_attempts
  DROP CONSTRAINT IF EXISTS intent_rail_attempts_rail_check,
  ADD CONSTRAINT intent_rail_attempts_rail_check
  CHECK (rail IN ('CCTP','AXELAR','LAYERZERO','VIA_LABS','WORMHOLE','THORCHAIN','GASZIP','HYPERLANE_NEXUS','OPTIMISM_NATIVE_BRIDGE','CHAINFLIP','MAYA','TELESWAP'));
