[profile.default]
src = "../src/contracts"
test = "../tests/contracts"
script = "../config/foundry/scripts"
out = "../build/foundry"
libs = ["../node_modules"]
cache_path = "../build/foundry-cache"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
allow_paths = [".."]
remappings = [
  "@openzeppelin/=../node_modules/@openzeppelin/",
  "src/=../src/"
]
